config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resource :accounts

  get 'user/me', to: 'users#me', as: 'my_settings'
  patch 'users/update_me', to: 'users#update_me', as: 'update_my_settings'
  get 'user/password', to: 'users#password', as: 'my_password'
  patch 'user/update_password', to: 'users#update_password', as: 'my_update_password'

  scope 'account', as: 'account' do
    resources :users
  end

  get 'activity/mine'
  get 'activity/feed'


  root to: 'activity#mine'
end

app/models/account.rb
class Account < ApplicationRecord
  resourcify
  has_many :users
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/friendlyable.rb
module Friendlyable
  extend ActiveSupport::Concern

  included do
    extend ::FriendlyId
    before_create :set_hash_id
    friendly_id :hash_id
  end

  def set_hash_id
    hash_id = nil
    loop do
      hash_id = SecureRandom.urlsafe_base64(9).gsub(/-|_/,('a'..'z').to_a[rand(26)])
      break unless self.class.name.constantize.where(:hash_id => hash_id).exists?
    end
    self.hash_id = hash_id
  end
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/user.rb
class User < ApplicationRecord
  include Friendlyable
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :invitable, :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # belongs_to :account, optional: true
  belongs_to :account

  # def account
  #   super || Account.new
  # end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def new
    redirect_to root_path unless current_user.account.nil?
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    if @account.save
      current_user.account = @account
      current_user.add_role :admin, @account
      current_user.save
      redirect_to root_path, success: "Your account has been created!"
    else
      render :new
    end
  end

  private
    def account_params
      params.require(:account).permit(:name, :addr1, :addr2, :city, :state, :zip, :country)
    end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def mine
  end

  def feed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  layout :layout_by_resource

  helper_method :current_account

  def current_account
    @current_account ||= current_user.account
    @current_account
  end

  protected
    def layout_by_resource
      if devise_controller?
        "devise"
      else
        "application"
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end

    def after_sign_up_path_for(resource)
      new_accounts_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :set_users, only: [:index]

  def index
  end

  def new
    @user = User.new
    set_choices
  end

  def edit
    set_choices
  end

  def me
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    respond_to do |format|
      if @user.update(user_password_params)
        bypass_sign_in(@user)
        format.html {
          redirect_to my_password_path,
          notice: 'Password was succesfully updated.'
        }
      else
        format.html { render :edit }
      end
    end
  end

  def update_me
    @user = current_user
    respond_to do |format|
      if @user.update(user_params)
        format.html {
          redirect_to my_settings_path,
          notice: 'Your information was succesfully updated.'
        }
      else
        format.html { render :me }
      end
    end
  end

  def create
    @user = User.unscoped.new(user_params.except("role"))
    @user.account = current_account
    @user.password = "password123"

    respond_to do |format|
      begin
        if @user.valid? && @user.invite!(current_user)
          @user.add_role user_params[:role].to_sym, current_account
          format.html {
            redirect_to account_users_path,
            notice: 'User was succesfully invited.'
          }
        else
          format.html { render :new }
        end
      rescue ActiveRecord::RecordNotUnique
        flash[:alert]= 'Email must be unique'
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params.except('role'))
        format.html {
          redirect_to account_users_path,
          notice: 'User was succesfully updated.'
        }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html {
        redirect_to account_users_path,
        notice: 'User was succesfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_users
      @users = current_account.users
    end

    def set_user
      @user = User.friendly.find(params[:id])
    end

    def set_choices
      @choices = []
      @choices << ["Admin", 'admin']
      @choices << ["User", 'user']
    end

    def user_params
      params.require(:user).permit(:name, :email, :role, :time_zone)
    end

    def user_password_params
      params.require(:user).permit(:password, :password_confirmation)
    end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(_opts = {})
    # return if flash[0][0] == :form_error
    flash.each do |msg_type, message|
      next if msg_type == :form_error
      concat(content_tag(:div, message.html_safe, {class: "alert #{bootstrap_class_for(msg_type)} fade in"}) do
        concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
        concat message.html_safe
      end)
    end
    nil
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }
    .join
    sentence = I18n.t('errors.messages.not_saved',
      count: resource.errors.count,
      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
      <div class="alert alert-error alert-block alert-fized">
        <h4>#{sentence}</h4>
        #{messages}
      </div>
    HTML

    html.html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/accounts/new.html.erb
<div class="row">
   <div class="col-lg-12">
      <div class="box">
         <div class="box-header">
            <h2>
               New Account Information
            </h2>
         </div>
         <div class="box-body">
            <%= form_for @account, html:{class: 'form-horizontal'} do |f| %>
               <% if @account.errors.any? %>
                 <div class="alert alert-error alert-block alert-fixed">
                   <h4>
                     <%= "#{pluralize(@account.errors.count, "error")} Prohibited this account from being saved:" %>
                     <%= @account.errors.full_messages.map{ |msg| content_tag(:li, msg) }.join %>
                   </h4>
                 </div>
               <% end %>
               <div class="form-goup">
                 <%= f.label :name, class: "control-label col-lg-2" %>
                 <div class="col-lg-10">
                   <%= f.text_field :name, placeholder: "Enter your Account\'s Name", class: 'form-control' %>
                 </div>
               </div>
               <div class="form-group">
                 <div class="col-lg-offset-2 col-lg-10">
                   <%= f.submit "Save", class: "btn btn-primary" %>
                 </div>
               </div>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/accounts/new.slim
.row
  .col-lg-12
    .box
      .box-header
        h2
          | New Account Information
        .box-body
          = form_for @account, html: { class: 'form-horizontal' } do |f|
            - if @account.errors.any?
              .alert.alert-error.alert-block.alert-fixed
                h4= "#{pluralize(@account.errors.count,"error")} prohibited this account from being saved: "
                == @account.errors.full_messages.map{|msg| content_tag(:li,msg)}.join
            .form-group
              = f.label :name, class: 'control-label col-lg-2'
              .col-lg-10
                = f.text_field :name, placeholder: 'Enter your Account\'s Name', class: 'form-control'
            .form-group
              .col-lg-offset-2.col-lg-10
                = f.submit 'Save', class: 'btn btn-primary'

app/views/activity/feed.html.erb
<h1>Activity#feed</h1>
<p>Find me in app/views/activity/feed.html.erb</p>

app/views/activity/feed.html.slim
h1 Activity#feed
p Find me in app/views/activity/feed.html.slim

app/views/activity/mine.html.erb
<h1>Activity#mine</h1>
<p>Find me in app/views/activity/mine.html.erb</p>

app/views/activity/mine.html.slim
h1 Activity#mine
p Find me in app/views/activity/mine.html.slim

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SassAppBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  </head>

  <body class="fixed skin-blue-light">
    <div class="wrapper">
      <%= render 'layouts/navigation/layout' %>
      <div class="content-wrapper">
        <%= flash_messages %>
        <%= yield %>
      </div>
      <%= render 'layouts/navigation/footer' %>
    </div>
  </body>
</html>

app/views/layouts/application.html.slim
doctype HTML
HTML
  head
    title Standup App
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all',\
     'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag href=\
    "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/\
    font-awesome.min.css"
  body.fixed.skin-blue-light
    .wrapper
      = render 'layouts/navigation/layout'
      .content-wrapper
        = flash_messages
        = yield
      = render 'layouts/navigation/footer'

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SassAppBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css' %>
  </head>

  <body class="login-page">
    <%= flash_messages %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.slim
doctype html
html
  head
    title Standup App
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' =>'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track':'reload'
    = stylesheet_link_tag href='//cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css'
  body.login-page
    = flash_messages
    = yield

app/views/layouts/navigation/_footer.html.erb
<footer class="">
   <div class="pull-right hidden-xs">
      Anything you want
   </div>
   <strong>
   Copyright © 2016
   <a href="#"> Company</a>
   </strong>All rights reserved.
</footer>

app/views/layouts/navigation/_footer.slim
footer.main-footer
  .pull-right.hidden-xs
    | Your SaaS app!!
  strong
    | &copy
    a href="#" Golden Ratio Consulting, LLC

app/views/layouts/navigation/_header.html.erb
<header class="main-header">
   <a class="logo" href="/">
   Standup App
   </a><!--Header Navbar: style can be found in header.less-->
   <nav class="navbar navbar-static-top" role="navigation">
      <div class="pull-left">
         <!-- <a class="logo" href="/t"> Teams </a>
         <a class="logo" href="/s"> Standups </a>
         <a class="logo" href=""> Submit a Standup </a> -->
          <% if user_signed_in? %>
            <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: "logo" %>
          <% else %>
            <%= link_to 'Register', new_user_registration_path, class: "logo" %>
            <%= link_to 'Login', new_user_session_path, class: "logo" %>
          <% end %>
      </div>
      <!--Navbar Right Menu-->
      <div class="navbar-custom-menu">
         <ul class="nav navbar-nav">
            <!--Notifications: style can be found in dropdown.less-->
            <li class="dropdown notifications-menu">
               <a class="dropdown-toggle" data-toggle="dropdown" href="#">
               <i class="fa fa-bell-o">
               </i><span class="label label-warning" style="display:none">
               NEW
               </span></a>
               <ul class="dropdown-menu" id="notification-container">

               </ul>
            </li>
            <!--User Account: style can be found in dropdown.less-->
            <li class="dropdown user user-menu">
               <a class="dropdown-toggle" data-toggle="dropdown" href="#">
               <img alt="" alt="" class="user-image" src=" " />
               <span class="hidden-xs">
               </span></a>
               <ul class="dropdown-menu">
                  <li class="header"></li>
                  <li class="divider"></li>
                  <li>
                     <a href="/user/me">
                     Profile
                     </a>
                  </li>

                  <li>
                     <a href="/account/users">
                     Settings
                     </a>
                  </li>
                  <li>

                  </li>

                  <li class="divider"></li>
                  <li>

                  </li>
               </ul>
            </li>
         </ul>
      </div>
   </nav>
</header>

app/views/layouts/navigation/_header.slim
header.main-header
  a.logo href='/'
    | Standup App
  .nav.navbar-static-top role="navigation"
    .navbar-custom-menu
      ul.nav.navbar-nav
        li.dropdown.messages-menu
          a.dropdown-toggle data-toggle="dropdown" href='#'
            i.fa.fa-envelope-o
            span.label.label-success 4
          ul.dropdown-menu
            li.header You have 4 messages
            li
              ul.menu
                li
                  a href='#'
                  .pull-left
                    img.img-circle [alt=("User Image") src="http://placehold.it/160x160"]

                  h4
                    | Sender Name
                    small
                      i.fa.fa-clock-o
                      | 5 mins
                  p Message Excerpt
                | \...
            li.footer
              a href="#" View all messages
        li.dropdown.notifications-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-bell-o
            span.label.label-warning 10
          ul.dropdown-menu
            li.header You have 10 notifications
            li
              ul.menu
                li
                  a href="#"
                    i.ion.ion-ios-people.info
                    | Notification title
                | \...
            li.footer
              a href="#" View all notifications
        li.dropdown.tasks-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            i.fa.fa-flag-o
            span.label.label-danger 9
          ul.dropdown-menu
            li.header You have 9 tasks
            li
              ul.menu
                li
                  /! Task Item
                  a href="#"
                  h3
                    | Design some buttons
                    small.pull-right 20%
                  .progress.xs
                    .progress-bar.progress-bar-aqua [ aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" style=("width: 20%") ]
                      span.sr-only 20% Complete
                  /! End Task Item
            li.footer
              a href="#" View all tasks
        li.dropdown.user.user-menu
          a.dropdown-toggle data-toggle="dropdown" href="#"
            img.user-image alt=("User Image") src="http://placehold.it/160x160"
            span.hidden-xs Austin Miles
          ul.dropdown-menu
            li.user-header
              img.img-circle [alt=("User Image") src="http://placehold.it/160x160"]
              P
                | Austin Miles - Web Developer
                small Member since July - 2016
            li.user-body
              .col-xs-4.text-center
                a href="#" Followers
              .col-xs-4.text-center
                a href="#" Sales
              .col-xs-4.text-center
                a href="#" Friends
            li.user-footer
              .pull-left
                a.btn.btn-default.btn-flat href="#" Profile
              .pull-right
                a.btn.btn-default.btn-flat href="#" Sign Out

app/views/layouts/navigation/_layout.html.erb
<%= render 'layouts/navigation/header' %>
<%= render 'layouts/navigation/sidebar' %>

app/views/layouts/navigation/_layout.slim
= render "layouts/navigation/header"
= render "layouts/navigation/sidebar"

app/views/layouts/navigation/_sidebar.html.erb
<div class="main-sidebar">
   <div class="sidebar">
      <div class="user-panel">
         <div class="pull-left image">
            <h3 class="header-circ">

            </h3>
         </div>
         <div class="pull-left info" style="vertical-align: middle; margin-top: 5px;">
            <p></p>
         </div>
         <div class="clearfix"></div>
         <span class="hidden-xs description">
            <p></p>
         </span>
      </div>
      <ul class="sidebar-menu">
         <li class="header">Overview</li>
         <li>

         </li>
         <li>

         </li>
      </ul>
      <ul class="sidebar-menu">
         <li class="header">Standups</li>
         <li>
            <a href="/t/s">
               <div class="fa fa-child"></div>
               <span>View</span>
            </a>
         </li>
      </ul>
   </div>
</div>

app/views/layouts/navigation/_sidebar.slim
.main-sidebar
  .sidebar
    .user-panel
      .pull-left.image
        img.img-circle alt=("User Image") src="http://placehold.it/160x160"
      .pull-left.info
        p User Name
        a href="#"
          i.fa.fa-circle.text-success
            | Online
    form.sidebar-form action="#" method="get"
      .input-group
        input.form-control name="q" placeholder="Search..." type="text"
        span.input-group-btn
          button#search-btn.btn.btn-flat name="Search" type="submit"
            i.fa.fa-search
    ul.sidebar-menu
      li.header HEADER
      li.active
        a href="#"
          span Link1

      li
        a href="#"
          span Link2
      li.treeview
        a href="#"
          span Multilevel
          i.fa.fa-angle-left.pull-right
        ul.treeview-menu
          li
            a href="#" Link 1 in level 2
          li
            a href="#" Link 2 in level 2

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/create.html.slim
h1 Users#create
p Find me in app/views/users/create.html.slim

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.erb
<div class="content-header">
   <h2>Users</h2>
</div>
<div class="content">
   <div class="row">
      <div class="col-lg-12">
         <div class="box box-primary">
            <div class="box-header">
               <h3 class="box-title">
                  <%= "Users in #{current_account.name}" %>
               </h3>
            </div>
            <div class="box-body">
               <div class="table-responsive">
                  <table class="table table-striped">
                     <thead>
                        <tr>
                           <th>Name</th>
                           <th>Email</th>
                           <th>Status</th>
                           <th>Role</th>
                           <th>Added at</th>
                           <th></th>
                        </tr>
                     </thead>
                     <tbody>
                        <% @users.each do |user| %>
                        <tr>
                           <td><%= user.name %></td>
                           <td><%= user.email %></td>
                           <td><%= user.accepted_or_not_invited? ? "Active" : "Invited" %></td>
                           <td><%= user.roles&.first&.name&.capitalize %></td>
                           <td><%= user.created_at.strftime('%D') %></td>
                           <td>
                              <%= link_to 'Edit', edit_account_user_path(user), class: 'btn btn-default btn-xs' %>
                              <%= link_to 'Destroy', account_user_path(user), {method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-warning btn-xs'} unless user.id == current_user.id %>
                           </td>
                        </tr>
                        <% end %>
                     </tbody>
                  </table>
               </div>
            </div>
            <div class="box-footer" style="height: 55px;">
               <span class="pull-right">
               <a class="btn btn-primary" href="<%= new_account_user_path %>">
               Add User
               </a></span>
            </div>
         </div>
      </div>
   </div>
</div>

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/new.html.slim
h1 Users#new
p Find me in app/views/users/new.html.slim

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>

app/views/users/update.html.slim
h1 Users#update
p Find me in app/views/users/update.html.slim